### ISSUE TITLE
Update schema for final 1.5.0

### ISSUE THREAD

**Issue by binzhou** [Relativ-IT/Butane-Schemas#6]
1.5.0 schema type is no longer experimental. The final schema has differences to the currently implemented 1.5.0-experimental, namely that `contents_local` is a support field of dropins.

**Comment by binzhou** [comment]
See: https://github.com/coreos/butane/blob/main/base/v0_5/schema.go

**Comment by Nemric** [comment]
Thanks for reporting this, will take a look ;)

**Comment by Nemric** [comment]
Hi, I did some rework on v1.4.0 and 1.5.0
`contents_local` for `dropins` is not the only change I've noticed

Please take a look by adding this :
`# yaml-language-server: $schema=https://raw.githubusercontent.com/Relativ-IT/Butane-Schemas/main/Butane-Schema-main.json`
at the beginning of your butane file  

Let me know :)

**Comment by binzhou** [comment]
cheers! thats working well for me thanks!

**Comment by Nemric** [comment]
Nice, I did push updates to Release, so you can delete the added reference to main branch.
If everything is right you can close the issue ;)

**Comment by binzhou** [comment]
Yep all works. Thanks for the fast fix!
